data:
  input_file_path: '../../data/raw_data/c4/c4.jsonl'
  output_folder_path: '../../data/filtered/c4'
  metadata_keys: 
    - "timestamp"
    - "url"
    - "language"
processing:
  remove_latex: false
  save_file: true
  filename: 'c4_filtered.csv'
  total_texts_filename: 'tot_texts_c4.txt'
